recalls_db:
  target: prod
  outputs:
    prod:
      type: postgres
      host: recalls_db
      user: "{{ env_var('RECALLS_DB_USERNAME') }}"
      password: "{{ env_var('RECALLS_DB_PASSWORD') }}"
      port: 5432
      dbname: recalls_db
      schema: public
      threads: 1
      keepalives_idle: 0
      connect_timeout: 10
      retries: 1